import Head from 'next/head'

export default function Resume() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Anton&family=Noto+Color+Emoji&display=swap" rel="stylesheet"></link>
      </Head>
      <main className=' min-h-screen bg-slate-50'>
      <section className='' >
          <nav className=' shadow-sm bg-slate-600' id='mainNav' >
            <ul className='flex justify-center my-5'>
              <li><a href="/" className='cursor-pointer'>Home</a></li>
              <li><p>|</p></li>
              <li><a href="/resume" className='cursor-pointer'>Resume</a></li>
              <li><p>|</p></li>
              <li><a href="/projects" className='cursor-pointer'>Projects</a></li>
            </ul>
          </nav>
      </section>
      <section>
      <center className=' px-6'>
        <iframe  className=' min-w-full min-h-screen'   src="/Brenden D. King-Resume.pdf" title='Resume' >
        </iframe>
    </center>
      </section>
      </main>
    </>
  )
}
